all:
	cd compute_gap; make all
	cd gt_eof; make all
	cd merge; make all
	cd rank_simple; make all
	cd rank_fast; make all
	cd rank_fast_improved; make all
	cd sa_correcting; make all
	cd update_gt; make all
	cd buffering_gap_values; make all
	cd test_distrib_file; make all

test:
	@cd compute_gap; make test
	@cd gt_eof; make test
	@cd merge; make test
	@cd rank_simple; make test
	@cd rank_fast; make test
	@cd rank_fast_improved; make test
	@cd sa_correcting; make test
	@cd update_gt; make test
	@cd buffering_gap_values; make test
	@cd test_distrib_file; make test

nuclear:
	cd compute_gap; make nuclear
	cd gt_eof; make nuclear
	cd merge; make nuclear
	cd rank_simple; make nuclear
	cd rank_fast; make nuclear
	cd rank_fast_improved; make nuclear
	cd sa_correcting; make nuclear
	cd update_gt; make nuclear
	cd buffering_gap_values; make nuclear
	cd test_distrib_file; make nuclear
