all:
	cd compute_gap; make all
	cd gt_eof; make all
	cd merge; make all
	cd rank; make all
	cd sa_correcting; make all
	cd update_gt; make all
	cd buffering_gap_values; make all
	cd fast_rank; make all
	cd fgm; make all

test:
	cd compute_gap; make test
	cd gt_eof; make test
	cd merge; make test
	cd rank; make test
	cd sa_correcting; make test
	cd update_gt; make test
	cd buffering_gap_values; make test
	cd fast_rank; make test
	cd fgm; make test

nuclear:
	cd compute_gap; make nuclear
	cd gt_eof; make nuclear
	cd merge; make nuclear
	cd rank; make nuclear
	cd sa_correcting; make nuclear
	cd update_gt; make nuclear
	cd buffering_gap_values; make nuclear
	cd fast_rank; make nuclear
	cd fgm; make nuclear
